name: evolve-favorites-to-amigas
status: open
created_at: '2026-04-25T04:29:48Z'
artifacts:
  - id: proposal
    path: artifacts/proposal.md
    status: done
  - id: design
    path: artifacts/design.md
    status: done
  - id: specs
    path: artifacts/specs.md
    status: done
  - id: tasks
    path: artifacts/tasks.md
    status: done
